apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-ustsample-deployment-tekton
  labels:
    app: ust-sample-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ust-sample-poc
  template:
    metadata:
      labels:
        app: ust-sample-poc
    spec:
      containers:
      - name: maven-ustsample-deployment-tekton
        image: 682452625784.dkr.ecr.us-east-1.amazonaws.com/mavensample-app-tekton:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000