apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: maven-ustsample-deployment-github
spec:
 selector:
   # Selector for Pods
   app: mavensample-app
 ports:
   # Port Map
 - port: 80
   targetPort: 3000
   protocol: TCP
 type: LoadBalancer
